# github_actions.yml

name: Sweep GHA Fix
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Update the Trunk Check setup instructions

      - name: Set up Trunk Check
        run: |
          # Provide detailed instructions for setting up Trunk Check
          # Add specific setup instructions for Trunk Check here

          - name: Set up Trunk Check
        run: |
          # Updated Trunk Check setup instructions
          # Add specific setup instructions for Trunk Check here

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Set up Trunk Check
        run: |
          # Provide detailed instructions for setting up Trunk Check
          # Reference the README.md file for detailed instructions
          # on how to set up the GitHub Actions integration

          # Detailed setup instructions for Trunk Check:
          # Add your detailed setup instructions here
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
  - name: Install dependencies
    run: npm ci
        - name: Run tests
        run: npm run test
