# github_actions.yml

name: Sweep GHA Fix
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your workflow steps here

      - name: Set up Trunk Check
        run: |
          # Instructions to set up Trunk Check
          # Reference the README.md file for instructions
          # on how to set up the GitHub Actions integration

          # Example:
          echo "Setting up Trunk Check"
          - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
