name: Check Job

on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        env:
          ENV_VAR: value
        strategy:
          fail-fast: false
        continue-on-error: false
        with:
          check-mode: payload
