name: Save Error Logs
on:
  workflow_run:
    workflows: ["Trunk Check Workflow"]
    types:
      - completed

permissions:
  contents: read

jobs:
  save_error_logs:
    name: Save Error Logs Job
    runs-on: ubuntu-latest

    steps:
      - name: Save Error Logs to File
        run: |
          echo 'Updated command to save error logs to file' >> ${{ env.ERROR_LOG_PATH }}
          cat ${{ env.ERROR_LOG_PATH }} > error_logs.txt
        continue-on-error: true
