name: Sweep GHA Fix

on:
  push:
    branches:
      - main

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix the issue
        run: |
          npm install
          npm build

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
                    git add .
          git commit -m "Fix the issue and commit changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
