name: Descriptive Workflow Name
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true

permissions:
  contents: read
  scripts: write

jobs:
  check:
    name: Descriptive Job Name
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
          - name: Trunk Check\n          uses: trunk-io/trunk-action@v1\n          with:\n            check-mode: payload
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
          check-mode: payload
