name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true
        check-base64: true

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Error Handling
        run: |
          echo "Error occured. Handling the error..."
      - name: Fallback Mechanism
        if: failure()
        run: |
          echo "Fallback mechanism: Sending a notification or running an alternative action..."
      - name: Try-Catch Block
        run: |
          try {
            echo "Executing the Trunk Check step..."
          } catch (error) {
            echo "An error occurred during the Trunk Check step: $error"
            echo "Handling the error..."
          }
        continue-on-error: true
        id: trunk_check
        continue-on-error: true
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
