name: Trunk Check
run-name: Trunk Check Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Print Error Logs
        if: failure()
        run: |
          echo 'Error logs: '
          cat ${{ github.workspace }}/path_to_error_logs
        uses: trunk-io/trunk-action@v2
        continue-on-error: true
        with:
          check-mode: report
