name: Trunk Check

env:
  NODE_VERSION: 16
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16.x
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
            - name: Trunk Check
        id: trunk-check
        run: |
          try {
        id: trunk-check
        run: |
          try {
            try {
            uses: trunk-io/trunk-action@v2
            with:
              check-mode: read
          } catch (error) {
            core.error(error.message)
            core.debug(error.stack)
            core.setFailed(error.message)
          }
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: read
