name: Check, Validate, and Deploy Workflow
  description: This workflow checks, validates, and deploys the code.
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Check and Validate Code
runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
            - name: Set up error handling
      run: echo "Error handling setup"
      - name: Log workflow status
      run: echo "Workflow status logged"

    # Error Handling and Logging
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
            - name: Install Dependencies
        run: echo "Installing Dependencies"
      - name: Perform Trunk Check
        continue-on-error: false
        uses: trunk-io/trunk-action@v3
        with:
          check-mode: ${{ fromJSON(inputs.payload).checkMode }}
          additional-input: ${{ fromJSON(inputs.payload).additionalInput }}
        with:
          check-mode: ${{ fromJSON(inputs.payload).checkMode }}
          additional-input: ${{ fromJSON(inputs.payload).additionalInput }}

          - name: Perform Trunk Check
        uses: trunk-io/trunk-action@v3
        with:
          check-mode: ${{ fromJSON(inputs.payload).checkMode }}
          additional-input: ${{ fromJSON(inputs.payload).additionalInput }}
        with:
          check-mode: payload
