name: Trunk Check
run-name: Trunk Check Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
          - name: Remove Existing Error Logs
      continue-on-error: false
      run: |
        echo 'Error logs: '
        cat ${{ github.workspace }}/correct_path_to_error_logs
          continue-on-error: true
          uses: trunk-io/trunk-action@v2
