name: Trunk Check
run-name: Trunk-Check-Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        description: Trigger for Trunk Check
        required: true

permissions:
  contents: read
  actions: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install @trunk/actions
          npx trunk check
