name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents:
    actions: write
    checks: write
    statuses: write

jobs:


defaults:
  run:
    working-directory: ./
    shell: bash

steps:
  - name: Setup Trunk CLI
    uses: trunk-io/setup-trunk-cli@v1
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        name: Trunk Action
  run: |
    try:
      uses: trunk-io/trunk-action@v1
    catch:
      run: |
        echo 'Error: Trunk Action Failed'
        exit 1
        with:
          check-mode: payload
