name: Trunk Check
run-name: Fix failing GitHub Actions run
on:
  permissions:
    contents: read
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}


    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
