name: Check Job
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true
    uses: ./.github/workflows/check-job.yaml

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        env:
          ENV_VAR: value
        strategy:
          fail-fast: false
        continue-on-error: true
        with:
          check-mode: payload
