name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: custom-group
      cancel-in-progress: false

    steps: 
      - name: Custom Check Job
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
      - name: Trunk Check
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
