name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
              catch(error) {
          # Add error handling and appropriate error messages here
          }
          finally {
          # Add a fallback mechanism here, such as sending a notification or running an alternative action
          }
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
