name: Descriptive Workflow Name
run-name: ${{ github.run_id }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Descriptive Workflow Name
        required: false

permissions:
  actions: run
  contents: read

jobs:
  check:
    name: Descriptive Job Name
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Descriptive Step Name
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
          other-input: value
