name: Trunk Check Workflow
run-name: ${{ github.run_id }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: Trunk Check workflow dispatch event
        required: true

permissions:
  contents: 'read'
  actions: 'read'

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: false

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
