name: Trunk Check
run-name: MeaningfulName
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false



jobs:
  check:
    name: MeaningfulJobName
    runs-on: DesiredRunnerEnvironment
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: MeaningfulStepName
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
