name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    types:
      - custom
    inputs:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Catch Errors
        run: |
          try {
            # Add fallback mechanism for action failure
            # Example: Send notification or run a different action
                      - name: Trunk Check
              uses: trunk-io/trunk-action@v1
              with:
                check-mode: payload
              continue-on-error: true
        continue-on-error: true
