name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
    try:
        # Log job configuration
        print('Job configuration completed successfully')
    except Exception as e:
        print('Job configuration error:', str(e))
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    permissions:
      contents: read
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        timeout-minutes: 5
