name: Trunk Check Workflow
  description: Workflow for running Trunk Check jobs

on:
  permissions:
    contents: read
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  trunk_check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    
    concurrency:
      group: valid-concurrency-group


    steps:
      - name: Run Trunk Check
        uses: trunk-io/trunk-action@v4
        with:
          check-mode: payload
