name: Descriptive Workflow Name
run-name: DesiredRunName
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  - workflow_dispatch

jobs:
  check:
    name: DescriptiveJobName
    runs-on: DesiredRunner
    concurrency:
      group: DesiredConcurrencyGroupHere
      cancel-in-progress: true

    steps:
      - name: DescriptiveAndInformativeStepName
        uses: new-desired-action@v1
        with:
          desired-input: DesiredValue
