name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Error Handling
        run: |
          try 
          {
      - name: Trunk Check
            uses: trunk-io/trunk-action@v1
          catch ::error
          
          fallback: |
            # Add fallback mechanism here
          
          notify: |
            # Add notification mechanism here
        with:
          check-mode: payload
