name: Descriptive Workflow Name
run-name: DesiredRunName
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  - workflow_dispatch

jobs:
  check:
    name: DescriptiveJobName
    runs-on: ubuntu-latest
    concurrency:
      group: DesiredConcurrencyGroupHere
      cancel-in-progress: true

    steps:
      - name: DescriptiveAndInformativeStepName
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.check_suite.head_sha }}
