name: Github Workflow
run-name: Workflow Run Name
on:
  workflow_dispatch:
    types: [workflow_dispatch]
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: write

jobs:
  check_workflow:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: trunk-io/trunk-action@v2
        with:
          with:
          mode: check
