name: Descriptive Workflow Name
run-name: DesiredRunName
on:
  workflow_dispatch:
    inputs:
      trigger-trunk-check:
      description: Trigger the Trunk Check workflow
      required: true

# permissions:
  # contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: DesiredRunner
    concurrency:
      group: DesiredConcurrencyGroup
      cancel-in-progress: false

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: modified-payload
          additional-input: value
