name: Trunk Check
run-name: TrunkCheckFix
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
      run: |
        # Add logging logic here
        echo "Trunk Check completed successfully"
      run: |
        # Add error handling logic here
        echo "Error occurred during Trunk Check"
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
