name: Check Workflow
run-name: ${{ github.event.inputs.checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.inputs.concurrencyGroup }}
      cancel-in-progress: false

    steps:
      - name: Error Handling and Logging
  continue-on-error: true
  uses: actions/checkout@v2
        uses: actions/checkout@v2
        with:
          check-mode: ${{ github.event.inputs.checkMode }}
