name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: 
    contents: write
    issues: write

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    continue-on-error: ${{ fromJSON(inputs.payload).checkJobContinueOnError }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: ${{ fromJSON(inputs.payload).checkMode }}
