name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      checkWorkflowRunName:
        description: For invocation by Trunk Check
        required: true
      checkJobName:
        description: For invocation by Trunk Check
        required: true
      checkJobRunsOn:
        description: For invocation by Trunk Check
        required: true
      concurrencyGroup:
        description: For invocation by Trunk Check
        required: true

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
