name: Check and Validate Workflow
  description: This workflow checks and validates the code before deployment.
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}

    # Error Handling and Logging
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Set up Repository
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v3
        with:
          check-mode: ${{ fromJSON(inputs.payload).checkMode }}
          additional-input: ${{ fromJSON(inputs.payload).additionalInput }}
        with:
          check-mode: payload
