name: Trunk Check
  on:
    push:
      branches:
        - main
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents:
    check: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v3
          - name: Print Detailed Error Logs
            if: failure()
                    - name: Print Detailed Error Logs
        if: failure()
        run: |
          echo 'Error logs:'
          cat /path/to/error/logs
              echo 'Error logs:'
              cat /path/to/error/logs
            run: |
              echo 'Error logs:'
              cat /path/to/error/logs
        with:
          check-mode: payload
