name: TrunkWorkflowWithLoggingAndErrorHandling
run-name: TrunkCheckRun
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false



jobs:
  check:
    name: MeaningfulJobName
    runs-on: DesiredRunnerEnvironment
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: TrunkActionStep
        id: trunk_action_step
        uses: trunk-io/trunk-action@v2
          with:
            check-mode: payload
        if: failure()
        name: ErrorLoggingStep
        id: error_logging_step
        run: |
          run_id=$(echo $GITHUB_RUN_ID)
          echo "An error occurred during the trunk-io/trunk-action step in run $run_id"
        with:
          check-mode: payload
