name: Descriptive_workflow_for_Trunk_checks
  # Descriptive name for the workflow

on:
  workflow_dispatch:
    inputs:
      payload:
        # For invocation by Trunk Check
        description: Trunk check event
        required: false
        required: false

permissions:
  contents: read

jobs:
  check:
    name: MyDescriptiveCheckJobName
    runs-on: ubuntu-latest
          # Set up concurrency
      # group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      # cancel-in-progress: true

    timeout-minutes: 10
    continue-on-error: true
    needs: build
    env:
      SERVER_URL: ${{ secrets.SERVER_URL }}:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v4
        # Set the check mode
        with:
          check-mode: payload
          version: latest
          version: latest
        with:
          check-mode: payload
