name: Trunk Check Workflow
run-name: Trunk Check Workflow Run
on:
    workflow_dispatch:
      inputs:
        payload:
          description: For invocation by Trunk Check
          required: true
  workflow_dispatch:
    inputs:
      payload:
        description: For invoking the generate-trunk-file workflow
        required: false
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
      - name: Trigger generate-trunk-file workflow
        uses: actions/checkout@v2
      - name: Run generate-trunk-file workflow
        uses: ./.github/workflows/generate-trunk-file.yaml
