name: Trunk Check
run-name: Trunk Check Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: [VALUE_TO_BE_REPLACED]
    concurrency:
      group: [VALUE_TO_BE_REPLACED]
      cancel-in-progress: [VALUE_TO_BE_REPLACED]

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
