name: Trunk Check
run-name: Trunk Check Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
          - name: Remove Existing Error Logs
        continue-on-error: false
        run: |
        run: |
          echo 'Remove existing error logs: '
        cat /path/to/error/logs
        continue-on-error: true
          uses: trunk-io/trunk-action@v2
