name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  on:
    failure:
      continue-on-error: true
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        continue-on-error: true
      - name: Log Error
        run: |
          echo "Failure occurred in Trunk Check workflow"
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
        with:
          check-mode: payload
