name: Descriptive Workflow Name
run-name: ${{ inputs.payload.checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    timeout-minutes: 10
    continue-on-error: true
    needs: build
    env:
      SERVER_URL: ${{ secrets.SERVER_URL }}:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v4
        with:
          check-mode: payload
          version: latest
        with:
          check-mode: payload
