name: Check Workflow - Clarity
run-name: ${{ github.event.inputs.checkWorkflowRunName }}
on:
  push

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.inputs.concurrencyGroup }}
      cancel-in-progress: false

   steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Run Necessary Actions
    run: echo 'Running necessary actions'
