name: Trunk Check
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents:
  check: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Log Error Logs
        run: |
          echo 'Error logs:'
          # Add command to capture or print error logs for further analysis
          # For example, you can use the following command to capture error logs in a file:
          # command_to_run > error_logs.txt
      - name: Log Error Logs
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
