name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    - name: Set up error handling
      run: |
        set -e
        trap 'exit 1' ERR

    steps:
      - name: Trunk Check
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          continue-on-error: ${{ github.event_name != 'pull_request' }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          check-mode: payload
