name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: true
        runs: 
         continue-on-error: true
         run: |
           if [[ -z ${{ github.event.inputs.payload }} ]]; then
             echo "Payload is required for workflow dispatch."; exit 1;
           fi

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Try Catch Block
        run: |
          try
      - name: Execute Trunk Check
            continue-on-error: ${{ failure() }}
            run: |\n  if [[ "${{ job.status }}" == "failure" ]]; then\n    echo "Trunk Check action failed. Exiting with error."; exit 1;\n  fi
        uses: trunk-io/trunk-action@v1
          continue-on-failure: true
          continue-on-error: true
      - name: Fallback Mechanism
            continue-on-error: true
            run: |
              echo "Trunk Check action failed. Sending notification or running alternative action."
        with:
  continue-on-error: true
        run: |
    if [[ "$?" -ne 0 ]]; then
      echo "Trunk Check action failed. Sending notification or running alternative action."; exit 1;
    fi
          
          run: |
            if [[ "$?" -ne 0 ]]; then
              echo "Trunk Check action failed."; exit 1;
            fi
