name: Descriptive Workflow Name
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Descriptive Job Name
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    
    # Update the concurrency configuration based on specific requirements
      concurrency:
        group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
    cancel-in-progress: true
        cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
