name: Descriptive Workflow Name
run-name: NewRunName
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Test Tool
        required: true

permissions:
  contents: write

jobs:
  verification_job:
    name: Verification Job
    runs-on: ubuntu-latest

    steps:
      - name: Run Test Tool
        uses: tool-org/tool-action@v2
        with:
          mode: test
