name: Descriptive Workflow Name
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}

    steps:
      - name: Trunk Check
        - name: Trunk Check
          uses: actions/checkout@v2
          with:
            check-mode: payload
            config-file: .trunk.yml
            additional-input: value
        with:
          check-mode: payload
