name: Trunk Check Workflow
run-name: Trunk Check Workflow Run
on:
    workflow_dispatch:
      inputs:
        payload:
          description: For invocation by Trunk Check
          required: true
  workflow_dispatch:
    inputs:
      payload:
        description: For invoking the generate-trunk-file workflow
        required: false
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on:
    workflow_dispatch:
      inputs:
        payload:
          description: For invoking the generate-trunk-file workflow
          required: false ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v4
        with:
          check-mode: full-payload
