name: Trunk Check Workflow
run-name: ${{ github.sha }}
on:
  push:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ubuntu-latest


    steps:
      - name: Run Trunk Check Action
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
