name: Trunk Check Fix

on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job

runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
concurrency:
  group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
  cancel-in-progress: true

steps:
  - name: Trunk Check
    uses: trunk-io/trunk-action@latest
    with:
      check-mode: payload

on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      - name: Trunk Check
        uses: trunk-io/trunk-action@latest
        with:
          check-mode: payload
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@latest
        with:
          check-mode: payload
