name: Updated Clarity Workflow
run-name: ${{ github.event.inputs.checkWorkflowRunName }}
on:
  push

permissions:
  contents: read

jobs:
  check:
    name: Updated Clarity Job
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.inputs.concurrencyGroup }}
      cancel-in-progress: false

   steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Display Workflow Logs
    run: echo ${{ job.status }}
  - name: Display Error Logs
    run: echo "Error Logs:" && cat ${{ github.workspace }}/error.log
    run: echo ${{ job.status }}
