name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read
  cancel-on-feature-failure: true

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    env:
      LOG_LEVEL: error
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
