name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Setup Actions Environment
        id: setup_env
        uses: actions/setup-node@v2
      - name: Error Handling Start
        run: |
          if [ "$ERROR" != "" ]; then
            echo "Workflow failed with error: $ERROR"
            exit 1
          fi  
      - name: Run Trunk Action
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
