name: Trunk Check
run-name: Trunk Check Workflow
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    concurrency:
      group: example-concurrency-group
      cancel-in-progress: false
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v2
        with:
          check-mode: payload
